name: Triggers

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" # Run at 17:00 UTC every day

jobs:
  show-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Show Trigger Information
        run: |
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Commit: $GITHUB_SHA"